defaults:
  - preset: default
  - hydra/job_logging: colorlog 
  - hydra/hydra_logging: colorlog
db:
  name: 'imagenet'  # available options are cifar10 and cifar100 at the moment
  root: '/dataset/ImageNet/Classification'  # path to save the data

# Logging and printing, and does not impact training
num_prints: 5
device: cuda
num_workers: 4
verbose: 0
show: 0   # just show the model and its size and exit

# Checkpointing, by default automatically load last checkpoint
checkpoint: True
continue_from: '' # Only pass the name of the exp, like `exp_dset=wham`
                  # this arg is ignored for the naming of the exp!
continue_best: false
restart: False # Ignore existing checkpoints
checkpoint_file: checkpoint.th
history_file: history.json

# Other stuff
seed: 2036

# Optimization related
epochs: 20
optim: sgd
lr: 0.001
momentum: 0.9
w_decay: 5e-4
batch_size: 2048
mixed: True  # if true, uses mixed precision training
beta2: 0.999
max_norm: 5
nesterov: True
alpha: 0.9

# learning rate scheduling
lr_sched: step # can be either step or plateau
step:
  step_size: 60
  gamma: 0.2
multistep:
  gamma: 0.1
plateau:
  factor: 0.5
  patience: 5
cosine:
  T_max: 10
  min_lr: 0.0001

# Models
model: 'mcunet-in4' # supported options are - mcunet-in1 | mcunet-in2 | mcunet-in4

# Gumbelnet option
gumbel:
 global_expand_ratio_list: [1, 3, 4, 5, 6]
 global_kernel_size_list: [3, 5, 7]
 gumbel_feature_extract_block_idx: 2 

flops_penalty: 0.001

log:''

rendezvous_file: ./rendezvous
ddp: True  # if set to true, uses all available GPUs.
rank:
world_size: 4

# Hydra config
hydra:
  run:
    dir: ./outputs/exp_${log}/${hydra.job.override_dirname}
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        # Remove all paths, as the / in them would mess up things
        # Remove params that would not,t impact the training itself
        # Remove all slurm and submit params.
        # This is ugly I know but probably faster than recoding Hydra
        exclude_keys: [
          'db.root',
          'hydra.job_logging.handles.file.filename',
          'num_prints', 'continue_from',
          'device', 'num_workers', 'print_freq', 'restart', 'verbose',
          'rendezvous_file', 'ddp', 'rank', 'world_size']
  # No clue what is the difference between hydra and job logging...
  job_logging:
    formatters:
      colorlog:
        datefmt: "%m-%d %H:%M:%S"
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: local.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr

  hydra_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr
